### ISSUE TITLE
Inconsistent behaviour with and without wildcard in graph definition

### ISSUE THREAD

**Issue by hanazuki** [mackerelio/go-mackerel-plugin-helper#13]
I'm in a little trouble with an inconsistent behaviour in the graph definition in this library.

For a graph definition returned by `GraphDefinition` method:
- When either its graph name or one of its metrics names contains a wildcard (`#` or `*`), `OutputValues` outputs a value that `FetchMetrics` has returned as `${graph_name}.${metrics_name}`
- When neither of them contains a wildcard, `OutputValues` outputs a value that `FetchMetrics` has returned as `${metrics_name}`.

So, when I want to output two metrics with the same name, say `udp.datagrams.sent` and `tcp.segments.sent`, from a single plugin, it cannot be possible since the values for the two metrics shares a key (`sent`) in the `FetchMetrics()` result.

It would be easy for you to find what happens in the following fragment of code.
Does the Mackerel.io team have any idea or a plan to resolve this inconsistency?
### Code to reproduce

``` go
package main

import (
    mp "github.com/mackerelio/go-mackerel-plugin-helper"
)

type plugin struct{}

func (p plugin) FetchMetrics() (map[string]interface{}, error) {
    return map[string]interface{}{
        "metrics.example1.aa": uint32(1),
        "aa": uint32(666), // <- output for metrics.example1.aa and metrics.example3.aa
        "metrics.example2.bb": uint32(2), // <- output for metrics.example2.bb
        "bb": uint32(667),
        "metrics.example3.aa": uint32(3),
    }, nil
}

func (p plugin) GraphDefinition() map[string]mp.Graphs {
    return map[string]mp.Graphs{
        "metrics.example1": {
            Unit:  "integer",
            Metrics: []mp.Metrics{
                {Name: "aa"},
            },
        },
        "metrics.example2": {
            Unit:  "integer",
            Metrics: []mp.Metrics{
                {Name: "*"},
            },
        },

        "metrics.example3": {
            Unit:  "integer",
            Metrics: []mp.Metrics{
                {Name: "aa"},
            },
        },
    }
}

func main() {
    helper := mp.NewMackerelPlugin(plugin{})
    helper.Run()
}
```
### Output

```
metrics.example1.aa     666     1456372059
metrics.example2.bb     2       1456372059
metrics.example3.aa     666     1456372059
```

**Comment by stanaka** [comment]
Thank you for reporting the issue.
I understand this behavior is not good, but it's difficult to change it.

I consider that a new field, say `NeedPrefix`, for Metrics definition. If this field is set, you need to add prefix, like `metrics.example1`, to output map values of `FetchMetrics`. And If wildcard is used as `Name`, this field become `true` implicitly.

Here's an example for `GraphDefinition`.

```
map[string]mp.Graphs{
    "metrics.example1": {
        Unit: "integer",
        Metrics: []mp.Metrics{
            {Name: "aa", NeedPrefix: true},
        },
    },
}
```

Does this make sense?

**Comment by hanazuki** [comment]
The solution sounds reasonable for maintaining compatibility and I'm glad if it's fixed. Thanks!
