### ISSUE TITLE
Graph definition is not working in some plugins.

### ISSUE THREAD

**Issue by supercaracal** [mackerelio/go-mackerel-plugin-helper#27]
For example Apache Solr:
https://github.com/mackerelio/mackerel-agent-plugins/pull/383

It reproduce if plugin used [go-mackerel-plugin-helper](https://github.com/mackerelio/go-mackerel-plugin-helper) without `#MetricKeyPrefix` interface implementation.

Graph name was different. For example Apache Solr:

| `#MetricKeyPrefix` | Graph Name (STDOUT) | Graph Definition (mackerel.io) |
| --- | --- | --- |
| Not implemented | solr.testcore.15minRateReqsPerSecond | Not working |
| Implemented | solr.solr.testcore.15minRateReqsPerSecond | It works! |

Is duplicate prefixes as specification correct?

Should we implement `#MetricKeyPrefix` to [plugins](https://github.com/mackerelio/mackerel-agent-plugins)?
Or,
Should we modify this [helper](https://github.com/mackerelio/go-mackerel-plugin-helper)?

https://github.com/mackerelio/go-mackerel-plugin-helper/blob/master/mackerel-plugin.go#L359

```
$ grep -rL 'MetricKeyPrefix() string' . | xargs grep -l 'mp "github.com/mackerelio/go-mackerel-plugin-helper"' | sort | nl
     1  ./mackerel-plugin-aws-ec2-ebs/lib/aws-ec2-ebs.go
     2  ./mackerel-plugin-aws-kinesis-streams/lib/aws-kinesis-streams_test.go
     3  ./mackerel-plugin-aws-lambda/lib/aws-lambda_test.go
     4  ./mackerel-plugin-conntrack/lib/cli.go
     5  ./mackerel-plugin-docker/lib/docker.go
     6  ./mackerel-plugin-fluentd/lib/fluentd.go
     7  ./mackerel-plugin-gcp-compute-engine/lib/gcp-compute-engine.go
     8  ./mackerel-plugin-gearmand/lib/gearmand.go
     9  ./mackerel-plugin-gostats/lib/mackerel-plugin-gostats.go
    10  ./mackerel-plugin-graphite/lib/graphite.go
    11  ./mackerel-plugin-inode/lib/inode.go
    12  ./mackerel-plugin-jmx-jolokia/lib/jmx-jolokia.go
    13  ./mackerel-plugin-jvm/lib/jvm.go
    14  ./mackerel-plugin-linux/lib/linux.go
    15  ./mackerel-plugin-mailq/lib/main.go
    16  ./mackerel-plugin-mongodb/lib/mongodb.go
    17  ./mackerel-plugin-multicore/lib/multicore.go
    18  ./mackerel-plugin-murmur/lib/murmur.go
    19  ./mackerel-plugin-nginx/lib/nginx.go
    20  ./mackerel-plugin-plack/lib/plack.go
    21  ./mackerel-plugin-proc-fd/lib/proc_fd.go
    22  ./mackerel-plugin-rabbitmq/lib/rabbitmq.go
    23  ./mackerel-plugin-rack-stats/lib/rack.go
    24  ./mackerel-plugin-snmp/lib/snmp.go
    25  ./mackerel-plugin-solr/lib/solr.go
    26  ./mackerel-plugin-squid/lib/squid.go
    27  ./mackerel-plugin-td-table-count/lib/mackerel-plugin-td-table-count.go
    28  ./mackerel-plugin-trafficserver/lib/trafficserver.go
    29  ./mackerel-plugin-unicorn/lib/unicorn.go
    30  ./mackerel-plugin-varnish/lib/varnish.go
    31  ./mackerel-plugin-windows-server-sessions/lib/sessions.go
    32  ./mackerel-plugin-xentop/lib/xentop.go
```

**Comment by syou6162** [comment]
We don't need to modify go-mackerel-plugin-helper. I check mackerel-plugin-solr and other plugins which does not implement `MetricKeyPrefix` are working properly.

ref: https://github.com/mackerelio/mackerel-agent-plugins/pull/383#issuecomment-319930823

**Comment by supercaracal** [comment]
I'm sorry, I misunderstood.
